#!/bin/bash

rm -f a.out hello.o hello2.o hello3.o libhello.so a.merged

GCC=gcc
# READELF=readelf
READELF=./readelf
# OBJCOPY=objcopy
OBJCOPY=./objcopy

PLUGIN=../plugin/.libs/annobin.so

$GCC -fplugin=$PLUGIN \
     -c \
     -fPIC \
     -Wall \
     -g \
     -fno-stack-protector \
     -fplugin-arg-annobin-stack-threshold=0x10 \
     -march=sandybridge \
 hello.c 

$GCC -fplugin=$PLUGIN \
     -O3 \
     -c \
     -fPIC \
     -fno-stack-protector \
     -fplugin-arg-annobin-global-file-syms \
     -march=native --save-temps \
 hello2.c 

$GCC -fplugin=$PLUGIN \
     -O2 \
     -c \
     -fPIE \
     -g3 \
     -fstack-protector-strong \
     -D_FORTIFY_SOURCE=2 \
     -fplugin-arg-annobin-no-stack-size-notes \
     -march=ivybridge \
     -grecord-gcc-switches \
 hello3.c \

$GCC -fplugin=$PLUGIN \
    -O2 \
    -fpic \
    -fstack-protector \
    -fplugin-arg-annobin-version \
    -shared \
    -mavx \
 hello_lib.c \
     -o libhello.so

$GCC -fplugin=$PLUGIN \
     -L . -pie \
     -Wl,-z,now,-z,relro \
 hello.o hello2.o hello3.o -lhello 

$OBJCOPY --merge-notes a.out a.merged
# cp a.out a.merged
$READELF --notes --wide a.merged
echo " "
# ../scripts/built-by.sh  --readelf=$READELF a.merged
# ../scripts/check-abi.sh --readelf=$READELF --inconsistencies a.merged
../scripts/hardened.sh  --readelf=$READELF --all a.merged hello3.o --all

